export const List = {
  orders: [
    {
      id: 8,
      clientName: "María Herminia",
      clientLastName: "Chebaia",
      orderNumber: "1119571984998-01",
      creationDate: "2021-03-23 09:33:02Z",
      province: "TUCUMÁN",
      city: "San Miguel De Tucumán",
      street: "Marcos Paz",
      number: "796",
      complement: "Piso 4 depto C",
      clientPhone: "543814132487",
      status: "Pendiente",
      cadeteriumId: 2,
      userId: 19,
    },
    {
      id: 14,
      clientName: "Fernanda ",
      clientLastName: "Aguero",
      orderNumber: "1119570217546-01",
      creationDate: "2021-03-23 10:03:40Z",
      province: "Tucumán",
      city: "Yerba Buena",
      street: "Avenida Aconquija",
      number: "1336",
      complement: null,
      clientPhone: "543816665138",
      status: "En camino",
      cadeteriumId: 2,
      userId: 5,
    },
    {
      id: 9,
      clientName: "romina",
      clientLastName: "barboza",
      orderNumber: "1119581919852-01",
      creationDate: "2021-03-23 10:32:02Z",
      province: "TUCUMÁN",
      city: "Departamento Capital (Tucumán)",
      street: "B. Matienzo",
      number: "77",
      complement: "1C",
      clientPhone: "5493814698393",
      status: "Pendiente",
      cadeteriumId: 2,
      userId: 5,
    },
    {
      id: 7,
      clientName: "Fernanda ",
      clientLastName: "Aguero",
      orderNumber: "1119570217546-01",
      creationDate: "2021-03-23 10:03:40Z",
      province: "Tucumán",
      city: "Yerba Buena",
      street: "Avenida Aconquija",
      number: "1336",
      complement: null,
      clientPhone: "543816665138",
      status: "En camino",
      cadeteriumId: 2,
      userId: 5,
    },
    {
      id: 1,
      clientName: "María Herminia",
      clientLastName: "Chebaia",
      orderNumber: "1119571984998-01",
      creationDate: "2021-03-23 09:33:02Z",
      province: "TUCUMÁN",
      city: "San Miguel De Tucumán",
      street: "Marcos Paz",
      number: "796",
      complement: "Piso 4 depto C",
      clientPhone: "543814132487",
      status: "Pendiente",
      cadeteriumId: 2,
      userId: 19,
    },
    {
      id: 3,
      clientName: "Graciela",
      clientLastName: "Carranza ",
      orderNumber: "1119583169361-01",
      creationDate: "2021-03-23 10:52:52Z",
      province: "Tucumán",
      city: "Departamento Capital (Tucumán)",
      street: "Congreso de Tucumán",
      number: "330",
      complement: "Piso 6 departamento E",
      clientPhone: "5493814498803",
      status: "En camino",
      cadeteriumId: 2,
      userId: 5,
    },
    {
      id: 2,
      clientName: "romina",
      clientLastName: "barboza",
      orderNumber: "1119581919852-01",
      creationDate: "2021-03-23 10:32:02Z",
      province: "TUCUMÁN",
      city: "Departamento Capital (Tucumán)",
      street: "B. Matienzo",
      number: "77",
      complement: "1C",
      clientPhone: "5493814698393",
      status: "Pendiente",
      cadeteriumId: 2,
      userId: 5,
    },
    {
      id: 13,
      clientName: "Victoria ",
      clientLastName: "Parrado ",
      orderNumber: "1119561076530-01",
      creationDate: "2021-03-23 09:17:56Z",
      province: "Tucumán",
      city: "San Miguel De Tucumán",
      street: "Avenida Belgrano",
      number: "2847",
      complement: null,
      clientPhone: "5493813508409",
      status: "Pendiente",
      cadeteriumId: 2,
      userId: 19,
    },
  ],
};

export const cadetes = [
  {
    id: 2,
    firstName: "Laura",
    lastName: "Gonzalez",
    email: "laura@gmail.com",
    phoneNum: "2954745678",
    admin: false,
    authorized: false,
    active: false,
    vehicle: "moto",
    cadeteriumId: null,
  },
  {
    id: 3,
    firstName: "Roberto",
    lastName: "Giovanni",
    email: "robertos@gmail.com",
    phoneNum: "29837456789",
    admin: false,
    authorized: false,
    active: false,
    vehicle: "moto",
    cadeteriumId: null,
  },
  {
    id: 4,
    firstName: "Jose",
    lastName: "Lopez",
    email: "joses@gmail.com",
    phoneNum: "2183745678",
    admin: false,
    authorized: false,
    active: false,
    vehicle: "moto",
    cadeteriumId: null,
  },
  {
    id: 19,
    firstName: "Martin",
    lastName: "Salar",
    email: "martin@gmail.com",
    phoneNum: "1231284912",
    admin: false,
    authorized: true,
    active: true,
    vehicle: "bicicleta",
    cadeteriumId: 2,
  },
  {
    id: 5,
    firstName: "ivan",
    lastName: "vera",
    email: "veraivandamian@gmail.com",
    phoneNum: "1231287689",
    admin: false,
    authorized: true,
    active: true,
    vehicle: "bicicleta",
    cadeteriumId: 2,
  },
];

export const cadeterias = [
  {
    id: 1,
    nameCompany: "Deliveroo",
    CUIT: "23324902349",
    email: "deliveroo@gmail.com",
    phoneNum: "2983745678",
    active: false,
    authorized: false,
    address: "Mitre 123",
  },
  {
    id: 2,
    nameCompany: "Uber",
    CUIT: "23377902349",
    email: "uber@gmail.com",
    phoneNum: "2983345678",
    active: true,
    authorized: true,
    address: "Tucuman 123",
  },
  {
    id: 3,
    nameCompany: "JustEat",
    CUIT: "25524902349",
    email: "justEat@gmail.com",
    phoneNum: "2943145678",
    active: false,
    authorized: false,
    address: "San Juan 123",
  },
];
